### ISSUE TITLE
我在安装spatial-correlation-sampler的时候遇到了一些问题

### ISSUE THREAD

**Issue by Siannodel** [KangBK0120/PERT#1]
我也尝试了在 Pytorch-Correlation-extension中寻求帮助，不过您使用的环境和我很类似，想问下您cuda版本、gcc版本以及当时装这个的时候遇到过什么问题没有。
非常感谢！

**Comment by KangBK0120** [comment]
Hi, please refer below

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```

```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

I have no trouble while installing the module with pip

**Comment by Siannodel** [comment]
thank you for your reply ！
I later successfully installed spatial-correlation-sampler and successfully ran your implementation. 
My environment is：

> pytorch 1.6
> gcc 5.3
> cuda: 10.2

I have another question. Did you do it 200 epochs during the training?

**Comment by KangBK0120** [comment]
Yes, I ran 200 epochs but it saturates earlier than 200. 

So there will be no significant visual difference after that epochs but I could not remember the exact epoch.

**Comment by Siannodel** [comment]
thank you for your reply ！
