### ISSUE TITLE
Can you provide a trained model for testing？

### ISSUE THREAD

**Issue by Siannodel** [KangBK0120/PERT#2]
First of all, thank you very much for your implementation！
I successfully trained the model and it seems to work well at the moment. But since I currently don't have SCUT-enstext data, I can't test its effect in real scenes. Can you provide a trained model for testing？

**Comment by KangBK0120** [comment]
Thanks for your interest!

I uploaded the pre-trained model. You can see the link in README.md(or [here](https://drive.google.com/file/d/1hJqsgWjAMVPSegq9KWdyXSrJeAgqomsA/view?usp=sharing)). The model is uploaded via Google drive.
If you have any problem, please tell me.

And I slightly modified the train codes. Thus the uploaded model is not the latest version. I will update the model and codes ASAP.

**Comment by Siannodel** [comment]
thank you for your reply ！
